apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: doosan
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: my-cluster-01
                  url: https://kubernetes.default.svc
          - list:
              elements:
                - name: doosan-c2c-back
                  path: tenants/doosan/apps/c2c-back
                - name: doosan-c2c-entels-back
                  path: tenants/doosan/apps/c2c-entels-back
                - name: doosan-c2c-matter-back
                  path: tenants/doosan/apps/c2c-back-matter-back
                - name: doosan-c2c-park-back
                  path: tenants/doosan/apps/c2c-back-park-back
  template:
    metadata:
      name: '{{.name}}-{{.cluster}}'
    spec:
      project: doosan
      source:
        repoURL: https://github.com/sunungchang-bespinglobal/doosan-argo-test.git
        targetRevision: main
        path: '{{.path}}'
      destination:
        server: '{{.url}}'
        namespace: doosan
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Rollout
          jsonPointers:
            - /spec/replicas