apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: doosan-default:argoproj.io/Rollout:default/doosan-default
  name: doosan-default
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 5
  rollbackWindow:
    revision: 3
  selector:
    matchLabels:
      app: doosan-default
      saas/tenant.name: doosan
      version: v1
  strategy:
    bluegreen:
      activeService: doosan-default-service
      autoPromotionEnabled: true
      previewService: doosan-default-service-preview
  template:
    metadata:
      annotations:
        hash: default
      labels:
        app: doosan-default
        saas/tenant.name: doosan
        tenancy: shared
        tier: basic
        version: v1
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: doosan
          image: saasone/aspnetapp:latest
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          name: doosan-default
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /file-data
              name: s3-storage
            - mountPath: /etc/secret/db
              name: db-secret
              readOnly: true
      tolerations:
        - effect: NoSchedule
          key: tier
          operator: Equal
          value: basic
        - effect: NoSchedule
          key: tenancy
          operator: Equal
          value: shared
      volumes:
        - name: s3-storage
          persistentVolumeClaim:
            claimName: doosan-s3-storage-pvc
        - name: db-secret
          secret:
            secretName: doosan-db-secret
